DataPath:
  ipts: 29298
ROI:
  mode: false
  xmax: null
  xmin: null
  ymax: null
  ymin: null
autoreduction: true
ob_auto_selection:
  days: 0
  hours: 3
  max_number_of_files: 12
  minutes: 0
  mode: true
  use_max_number_of_files: true
edge_cropping:
  automatic: true
ring_removal:
  mode: true
  algorithm: "Vos"
  list_algorithm: ["Vos", "bm3d"]
acquisition_time_coefficient: 5
